/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author Lucas
 */
public class TelaTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form TelaTriangulo
     */
    public TelaTriangulo() {
        initComponents();
        panPainel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spiA = new javax.swing.JSlider();
        spiB = new javax.swing.JSlider();
        spiC = new javax.swing.JSlider();
        btnBotao = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        panPainel = new javax.swing.JPanel();
        lblRes = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Segmento A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, 115, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Segmento B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 58, 115, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Segmento C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 107, 115, -1));

        spiA.setMaximum(20);
        spiA.setValue(0);
        spiA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spiAStateChanged(evt);
            }
        });
        getContentPane().add(spiA, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 15, -1, -1));

        spiB.setMaximum(20);
        spiB.setValue(0);
        spiB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spiBStateChanged(evt);
            }
        });
        getContentPane().add(spiB, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 64, -1, -1));

        spiC.setMaximum(20);
        spiC.setValue(0);
        spiC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spiCStateChanged(evt);
            }
        });
        getContentPane().add(spiC, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 113, -1, -1));

        btnBotao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBotao.setText("Verificar");
        btnBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/triangulo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 6, -1, -1));

        txtA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtA.setForeground(new java.awt.Color(153, 153, 153));
        txtA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 6, 40, -1));

        txtB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtB.setForeground(new java.awt.Color(153, 153, 153));
        txtB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 55, 40, -1));

        txtC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtC.setForeground(new java.awt.Color(153, 153, 153));
        txtC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 104, 40, -1));

        lblRes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRes.setForeground(new java.awt.Color(0, 0, 204));
        lblRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRes.setText("Forma ou não forma?");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(204, 0, 0));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("Tipo de triângulo.");

        javax.swing.GroupLayout panPainelLayout = new javax.swing.GroupLayout(panPainel);
        panPainel.setLayout(panPainelLayout);
        panPainelLayout.setHorizontalGroup(
            panPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPainelLayout.createSequentialGroup()
                        .addComponent(lblRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(panPainelLayout.createSequentialGroup()
                        .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panPainelLayout.setVerticalGroup(
            panPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPainelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 600, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotaoActionPerformed
        // TODO add your handling code here:
        panPainel.setVisible(true);
        int a = spiA.getValue();
        int b = spiB.getValue();
        int c = spiC.getValue();
        if (a<b+c && b<c+a && c<a+b){
            lblRes.setText("Formam um Triângulo!");
            if (a==b && b==c){
                lblTipo.setText("Equilátero");
            } else if (a!=b && b!=c && c!=a){
                lblTipo.setText("Escaleno");
            }else{
                lblTipo.setText("Isóciles");
            }
        }else{
            lblRes.setText("Não formam um Triângulo!");
            lblTipo.setText("-----");
        }
    }//GEN-LAST:event_btnBotaoActionPerformed

    private void spiAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spiAStateChanged
        // TODO add your handling code here:
        txtA.setText(String.valueOf(spiA.getValue()));
    }//GEN-LAST:event_spiAStateChanged

    private void spiBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spiBStateChanged
        // TODO add your handling code here:
        txtB.setText(String.valueOf(spiB.getValue()));
    }//GEN-LAST:event_spiBStateChanged

    private void spiCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spiCStateChanged
        // TODO add your handling code here:
        txtC.setText(String.valueOf(spiC.getValue()));
    }//GEN-LAST:event_spiCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel panPainel;
    private javax.swing.JSlider spiA;
    private javax.swing.JSlider spiB;
    private javax.swing.JSlider spiC;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    // End of variables declaration//GEN-END:variables
}
